apiVersion: apps/v1
kind: Deployment
metadata:
  name: activemq-deployment
  labels:
    app: activemq
    app.kubernetes.io/name: activemq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: activemq
  template:
    metadata:
      labels:
        app: activemq
    spec:
      containers:
        - name: activemq
          image: apache/activemq-classic:latest
          ports:
            - containerPort: 61616
              name: tcp
            - containerPort: 8161
              name: admin
          env:
            - name: ACTIVEMQ_NAME
              value: activemq
            - name: ACTIVEMQ_USERNAME
              value: admin
            - name: ACTIVEMQ_PASSWORD
              value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: activemq
  labels:
    job: activemq
    app: activemq
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: activemq
  ports:
    - name: activemq-tcp
      protocol: TCP
      port: 61616
      targetPort: 61616
    - name: activemq-admin
      protocol: TCP
      port: 8161
      targetPort: 8161
