kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jaeger-operator-in-services
  namespace: services
subjects:
  - kind: ServiceAccount
    name: jaeger-operator
    namespace: monitoring
roleRef:
  kind: Role
  name: jaeger-operator
  apiGroup: rbac.authorization.k8s.io
