package com.example.bettingService.entity;

import lombok.Getter;
import lombok.Setter;

public enum BetStatus {
    BET_PLACEMENT_VERIFYING_CREATOR_AND_GAME,
    BET_PLACEMENT_VERIFYING_CREATOR_PAYMENT,
    BET_PLACEMENT_WAITING_FOR_ACCEPTOR,
    BET_PLACEMENT_REJECTED,
    BET_PLACEMENT_VERIFYING_CANCELLED,
    BET_PLACEMENT_CANCELLED,
    BET_ACCEPTOR_VERIFYING_ACCEPTOR_AND_GAME,
    BET_ACCEPTOR_VERIFYING_ACCEPTOR_PAYMENT,
    BET_ACCEPTOR_NOT_ACCEPTED,
    BET_ACCEPTOR_REJECTED,
    BET_CONFIRMED_WAITING_FOR_GAME_RESULT,
    BET_CONFIRMED_PROCESSING_GAME_RESULT,
    BET_CONFIRMED_VERIFYING_PAYOUT,
    BET_CONFIRMED_COMPLETED
}