CREATE TABLE product (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  product_id INT NOT NULL,
  name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  price DECIMAL DEFAULT NULL
);

CREATE TABLE bet (
  id INT AUTO_INCREMENT PRIMARY KEY,
  bet_value_creator FLOAT NOT NULL,
  bet_value_taker FLOAT NOT NULL,
  bet_on_home_team_creator BOOLEAN NOT NULL,
  bet_status VARCHAR(250) NOT NULL,
  payout_creator FLOAT NOT NULL,
  payout_taker FLOAT NOT NULL,
  bet_creator_id INT NOT NULL,
  bet_taker_id INT,
  game_id INT NOT NULL,
    CHECK (bet_status in (
      'BET_PLACEMENT_VERIFYING_CREATOR_AND_GAME',
        'BET_PLACEMENT_VERIFYING_CREATOR_PAYMENT',
        'BET_PLACEMENT_WAITING_FOR_ACCEPTOR',
        'BET_PLACEMENT_REJECTED',
        'BET_PLACEMENT_VERIFYING_CANCELLED',
        'BET_PLACEMENT_CANCELLED',
        'BET_ACCEPTOR_VERIFYING_ACCEPTOR_AND_GAME',
        'BET_ACCEPTOR_VERIFYING_ACCEPTOR_PAYMENT',
        'BET_ACCEPTOR_NOT_ACCEPTED',
        'BET_ACCEPTOR_REJECTED',
        'BET_CONFIRMED_WAITING_FOR_GAME_RESULT',
        'BET_CONFIRMED_PROCESSING_GAME_RESULT',
        'BET_CONFIRMED_VERIFYING_PAYOUT',
        'BET_CONFIRMED_COMPLETED'
    ))
);